---
- name: Manage GNS3 devices
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check Ansible version
      command: ansible --version
      register: ansibleVersion

    - name: Print version
      debug:
        msg: "Ansible Version: {{ ansibleVersion.stdout }}"
